
package com.carbontrack.utils;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;

public class PDFUtil {

    public static byte[] generateMonthlyReportBytes(String username, double totalCO2, int points) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, baos);
            document.open();

            Font title = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font body = new Font(Font.FontFamily.HELVETICA, 12);

            document.add(new Paragraph("CarbonTrack Monthly Report", title));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("User: " + username, body));
            document.add(new Paragraph("Total CO2 Emissions: " + totalCO2 + " kg", body));
            document.add(new Paragraph("Reward Points: " + points, body));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by CarbonTrack System"));

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            e.printStackTrace();
            return new byte[0];
        }
    }
}
